name: learn-github-actions
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
            steps:
                - run: echo "Output test"
                - uses: actions/checkout@v2
                - run: |
                    ls -al
                    cd .githib/workflows
                    ls -al